@startuml ElectricalMeterSimple
class ElectricalMeter
class Outlet
interface PoweredDevice

ElectricalMeter <-- Outlet : getState
Outlet <-- ElectricalMeter : updateState
Outlet <-- PoweredDevice : setState

@enduml