@startuml architecture

interface Device {
    + getState(): DeviceState
}

interface Controller {
    + receiveCommand(Command)
}

interface DeviceManager {
    + getDevices(): List<Device<?>>
    + updateDeviceState(DeviceId, DeviceState)
}

interface DeviceViewer {
    + updateDeviceState(DeviceId, DeviceState)
}

Controller -> DeviceManager: runs command
DeviceManager -- Device
DeviceManager -> DeviceViewer: sends update
DeviceViewer -> Controller: sends command

@enduml
