@startuml

interface Device<T> {
    + getInfo(): DeviceInfo
    + getState(): T
}

interface ToggleableDevice<T> extends Device {
	+ isToggled(): Boolean
	+ toggle(): void
}

interface AdjustableDevice<T> extends Device {
	+ setState(T)
	+ getMinValue(): T
	+ getMaxValue(): T
}

@enduml
