@startuml domain

' left to right direction

interface Controller {}
interface DeviceManager {}
interface DeviceState {}
interface Device {
    + getState(): DeviceState
}

interface AdjustableDevice extends Device {
    + setState(DeviceState)
}
interface ToggleableDevice extends Device {
    + toggle()
}

Controller -- DeviceManager
DeviceState -- Device
Device -- DeviceManager

@enduml
