@startuml

interface Logger extends DeviceViewer {

    + void setOutputStream(OutputStream outputStream);

    + void log(String string);
}

interface DeviceViewer {
    + void updateDeviceState(DeviceId deviceId, DeviceState deviceState);

    + void removeDevice(DeviceId deviceId);

    + void start(Controller controller);

}


class LoggerImpl implements Logger {
    + LoggerImpl(OutputStream outputStream)
}

class TimeStampLogger implements Logger {
   + TimeStampLogger(Logger logger, Clock clock)
}

class WarningLogger implements Logger {
    + public WarningLogger(Logger logger)
}


@enduml
