@startuml

interface Logger {

    + void setOutputStream(OutputStream outputStream);

    + void log(String string);
}

interface DeviceViewer {
    + void updateDeviceState(DeviceId deviceId, DeviceState deviceState);

    + void removeDevice(DeviceId deviceId);

    + void start(Controller controller);

}


class LoggerImpl {
    + LoggerImpl(OutputStream outputStream)
}

class TimeStampLogger {
    TimeStampLogger(Logger logger, Clock clock)
}

class WarningLogger {
    public WarningLogger(Logger logger)
}

Logger --|> DeviceViewer
LoggerImpl --|> Logger
WarningLogger --|> Logger
TimeStampLogger --|> Logger

@enduml
