@startuml

interface Controller {
  + getDeviceManager(): DeviceManager
  + getScheduler()
  + getLogger()
  + getViewManager()
}

interface ViewManager() {
	addView(View)
	removeView(View)
	updateAll()
}

interface DeviceManager {
  + connectDevice(?)
  + disconnectDevice(uuid)
  + getConnectedDevices(): DeviceView ? 
  + getConnectableDevices(): ?

  + signalDevice(?)
  + toggleDevice(?) ?
  + setAdjustableDevice(?) ?
}


interface Logger extends View {
	addOuputStream(OutputStream)
	removeOuptutStream(OutputStream)
}

interface JavaFXView extends View {
}

interface View  {
	getActiveDeviceViews()
}

interface DeviceView<Device> {
	void update()
	void notify()
}

@enduml
