@startuml scheduler

' left to right direction

interface TimeScheduler<T extends Comparable<T>> {
	+ addSchedule(timeBounds: Bounds<LocalTime>, paramBounds: Bounds<T>)
	+ removeSchedule(ScheduleId)
	+ getSchedules(): Map<ScheduleId, TimeSchedule<T>>
	+ checkSchedule(currentTime: LocalTime, currentParameter: T): ParameterResult
}

interface TimeSchedulerController<T extends Comparable<T>> {
	+ addSchedule(timeBounds: Bounds<Integer>, paramBounds: Bounds<T>)
	+ removeSchedule(ScheduleId)
	+ setView(TimeSchedulerView<T>)
}

interface TimeSchedulerView<T extends Comparable<T>> {
	+ updateSchedules(Map<ScheduleId, TimeSchedule<T>> schedules)
}

TimeSchedulerController -- TimeScheduler
TimeSchedulerController -- TimeSchedulerView

@enduml
