@startuml scheduler

interface SchedulerCommand {
	+ execute(): void
}

interface TimeScheduler<T> {

}

interface TemperatureCommands {
	+ SchedulerCommand doHeat()
	+ SchedulerCommand stopAll()
	+ SchedulerCommand doCool()
}

class TemperatureScheduler<Temperature> implements TimeScheduler {
	+ TemperatureScheduler(TemperatureCommands)
}

class TimeSchedule<T> {
	+ timeRange(): Bounds<LocalTime>
	+ paramRange(): Bounds<T>
}

@enduml
