@startuml

interface Scheduler<T> {
	+ addSchedule(Schedule<T>)
	+ removeSchedule(?)
	+ getSchedules(): Set<Schedule<T>>
	+ checkSchedule(time, param)
}

class TemperatureScheduler<Temperature> implements Scheduler {}

interface Schedule {
	+ checkSchedule(time, param)
}

class ScheduleImpl<T> implements Schedule {
	' // - timeConstraints: Set<Predicate<LocalTime>>
	' // - paramConstraints: Set<Predicate<T>>
	- constraints: Set<Pair<Predicate<LocalTime>, Predicate<T>>>
	- commands: Set<BiConsumer<T>>
}

@enduml
