@startuml scheduler

interface SchedulerCommand {
	+ execute(): void
}

interface Scheduler<T> {
	+ addSchedule(Schedule<T>)
	+ removeSchedule(?)
	+ getSchedules(): Set<Schedule<T>>
	+ checkSchedule(LocalDateTime, T)
}

interface TemperatureCommands {
	+ SchedulerCommand doHeat()
	+ SchedulerCommand stopAll()
	+ SchedulerCommand doCool()
}

class TemperatureScheduler<Temperature> implements Scheduler {
	+ TemperatureScheduler(TemperatureCommands)
}

interface Schedule<T> {
	+ checkSchedule(LocalDateTime, T)
}

class ScheduleImpl<T> implements Schedule {
	' - constraints: Set<Pair<Predicate<LocalTime>, Bounds<T>>>
	- constraints: Set<Pair<Bounds<LocalTime>, Bounds<T>>>
}

@enduml
